[toolchain]
anchor_version = "0.30.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
solanapdas = "6yFm2AyqNS3i1xqyhD76phrQCx5FEKGPQjMwBpsdAkKa"

[programs.localnet]
solanapdas = "6yFm2AyqNS3i1xqyhD76phrQCx5FEKGPQjMwBpsdAkKa"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
